
.INCLUDE "M32DEF.INC"
.ORG $200
.DB $14, $28, $24, $22, $48, $44, $42, $88, $84, $82, $81, $41, $21, $11, $12, $18
.ORG 0
RJMP  main
      
main: 	
		
		ORI R23, 0
      	OUT TCCR0, R23

	

		.DEF FLAG = R29	
		.DEF AVAL = R20	
		.DEF DOVOM = R22
		.DEF AMALGAR = R21
		.DEF ISAMAL = R23
		.DEF JAVABJAM = R24
		.DEF TEMP = R25
		.DEF COUT = R26
		.DEF DOUT = R27
		.DEF BOUT = R28

		CLR FLAG
		CLR AVAL
		CLR DOVOM
		CLR AMALGAR
		CLR ISAMAL
		CLR JAVABJAM
		CLR TEMP
		CLR COUT
		CLR BOUT
		CLR DOUT


		LDI R16, $F0
		OUT DDRA, R16
		CLR R17
		OUT SFIOR, R17
		LDI R18,$FF
		OUT DDRB, R18
		OUT DDRC, R18
		OUT DDRD, R18
		OUT PORTA, R18 ; 4 taye chap DDRA hichi, 4 taye rast ke DDRA eshun 0 e, alan PORTA eshun 1 e ke mishan khoruji
		CLR R23
		CLR R18
l2:		LDI R18,$80	
l1:		OUT PORTA, R18
		IN R16, PINA
		CLR TEMP
		OR TEMP, R16
		ANDI TEMP, $0F
		CPI TEMP, $00
		BRNE next
		CLC
		ROR R18
		INC R17
		CPI R17,4
		BRNE l1
		CLR R17
		RJMP l2

next:	CLR TEMP
		IN   TEMP, PINA 
		ANDI TEMP, $0F ; CHECKING THE RELEASE OF THE PUSHED BUTTON
		CPI  TEMP, $00
		BRNE NEXT
		
		OUT TIFR, TEMP
		CLR TEMP

		CLR R19
		OR R19, R16
		ANDI R19, $0F
		OR R19,R18
		LDI R30, 0
		LDI R31,$04
		CLR R17

l4: 	LPM R0,Z
		CP R0,R19
		BREQ l3
		INC R30
		INC R17
		CPI R17,16
		BRNE l4

l3:		CPI R30, $0F
		BREQ RESTART
		CPI FLAG, 0
		BREQ FLAG0 ; DEFAULT ADAD AVAL 1 
		CPI FLAG, 1
		BREQ FLAG1 ; DEFAULT ADAD AVAL 2
		CPI FLAG, 2
		BREQ FLAG2 ; DEFAULT AMALGAR
		CPI FLAG, 3
		BREQ FLAG3 ; DEFAULT ADAD DOVOM 1
		CPI FLAG, 4
		BREQ FLAG44 ; DEFAULT ADAD DOVOM 2
		CPI FLAG, 5
		BREQ FLAG55 ; DEFAULT ADAD DOVOM 2

FLAG55: JMP FLAG5
FLAG44: JMP FLAG4

RESTART:
		CLR FLAG
		CLR AVAL
		CLR DOVOM
		CLR AMALGAR
		CLR COUT
		CLR DOUT
		CLR BOUT
		OUT PORTC, COUT
		OUT PORTD, DOUT
		OUT PORTB, BOUT
		RJMP l2		

FLAG0:	CLR AVAL
		OR AVAL, R30
		LDI FLAG, 1
		OUT PORTB, AVAL
		MOV R1, AVAL
		RJMP l2

FLAG1:	CPI R30, $0A
		BREQ SETAMAL1
		CPI R30, $0B
		BREQ SETAMAL2		
		CPI R30, $0C
		BREQ SETAMAL3
		CPI R30, $0D
		BREQ SETAMAL4
		CLR TEMP
		clr r27
       MOV R27, R1
       SWAP R27
       OR R27, R30
       OUT PORTB, R27
       
       LDI R24, 10
       MUL R1, R24
       ADD R0, R30
       mov r1, r0
	   LDI FLAG, 2
       RJMP L2

SETAMAL1: 
		LDI ISAMAL, 1
		RJMP FLAG2
SETAMAL2: 
		LDI ISAMAL, 2
		RJMP FLAG2
SETAMAL3: 
		LDI ISAMAL, 3
		RJMP FLAG2
SETAMAL4: 
		LDI ISAMAL, 4
		RJMP FLAG2

FLAG2:	CPI R30, $0A
		BRLO EDITAVAL		
		OR AMALGAR, R30
		LDI FLAG, 3
		OUT PORTB, DOVOM
		OUT PORTB, DOVOM
		RJMP l2

EDITAVAL:
		CLR AVAL
		RJMP FLAG0

FLAG3:	
		LDI FLAG, 4
		OUT PORTB, R30
       MOV R2, R30
       RJMP L2

FLAG4:	
		CPI R30, $0E
		BREQ CAL
		clr r23
       clr r27
       MOV R27, R2
       SWAP R27
       OR R27, R30
       OUT PORTB, R27
        
	 
       
       LDI R24, 10
       mov r3, r1
       MUL R2, R24
       ADd R0, R30
       mov r2, r0
       mov r1, r3
	   LDI FLAG, 5
       RJMP L2

EDITDOVOM:
		CLR DOVOM
		RJMP FLAG3

FLAG5:	CPI R30, $0A
		BRLO EDITDOVOM	
		CPI R30, $0E
		BREQ CAL

CAL:	CLR R30
		CLR R31
		CLR R26
		CLR R27
		CLR TEMP
		OUT PORTB, TEMP
		CPI AMALGAR, $0A
		BREQ TAGHSIM
		CPI AMALGAR, $0B
		BREQ ZARB
		CPI AMALGAR, $0C
		BREQ TAFRIGH
		CPI AMALGAR, $0E
		BREQ JAM		
TAGHSIM:   
      
       CP R1, R2
       BRLO CLEARPRINT
       INC R26
       SUB R1, R2
       RJMP TAGHSIM
       
ZARB:  
       MOV R3, R1
       MUL R2, R3
       MOVW R26, R0
       RJMP CLEARPRINT
TAFRIGH:

      SUB R1, R2
      MOV R26, R1
      RJMP CLEARPRINT

JAM:
      ADD R1, R2
      MOV R26, R1
      RJMP CLEARPRINT
      
CLEARPRINT:
      
      CLR R29
      CLR R28
YEKANCLEAR:
      CPI R27, 0
      BRNE CNN
      CPI R26, 10
      BRLO DAHGANCLEAR

CNN:
      ADIW R28, 1
      SBIW R26, 10
      RJMP YEKANCLEAR
      
DAHGANCLEAR:
      CPI R29, 0
      BRNE CNN2
      CPI R28, 10
      BRLO SADGANCLEAR
CNN2:
      INC R30
      SBIW R28, 10
      RJMP DAHGANCLEAR
      
SADGANCLEAR:
      CPI R30, 10
      BRLO PRINT
      INC R31
      SUBI R30, 10
      RJMP SADGANCLEAR

PRINT:
      SWAP R28
      OR R26, R28
      OUT PORTC, R26
      
      SWAP R31
      OR R30, R31
      OUT PORTD, R30
      RJMP L2
		
PRINTCD: 
		OUT PORTC, COUT
		OUT PORTD, DOUT
		CLR TEMP
		OUT PORTB, TEMP 
		CLR COUT
		CLR DOUT
		CLR AVAL
		CLR DOVOM
		CLR FLAG
		RJMP l2
		


